Features/hero adventages
kotikm81/codehunters-team-proj pull request #23
Opened 2021-04-02 18:17 UTC by PawelYarko

2021-04-02 19:06 UTC, kotikm81 requested changes

2021-04-02 19:06 UTC, kotikm81 commented on src/partials/advantages.html
> +        <h1 class="advantages-title visually-hidden">Advantages</h1>
Мне не нравятся имена классов по БЭМ. Извини, но доколупаюсь. Лучше так advantages__titl, advantages__list, advantages__item, advantages__icon....

2021-04-02 19:06 UTC, kotikm81 commented on src/partials/hero.html
> +    <div class="container">
Аналогично hero__position, hero__title, hero__description, hero__tex, hero__container, hero__thumb, hero__img

2021-04-02 20:42 UTC, PawelYarko commented on src/partials/advantages.html
> +        <h1 class="advantages-title visually-hidden">Advantages</h1>
все ок, наоборот хорошо что прикапываешься)

2021-04-03 06:58 UTC, kotikm81 requested changes

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/advantages.html
> +                <svg class="advantages-item__icon">
вместо advantages-item__icon просто advantages__icon (у тебя нет блока advantages-item, чтобы давать такое имя классу элемента )

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/advantages.html
> +                <p class="advantages-item__text">Адаптированная авторская программа ВНО</p>
аналогично просто advantages__text

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/hero.html
> +            <div class="hero-information__container">
hero__container

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/hero.html
> +                    <span class="hero-description__text">Просто не будет.</span>
hero__text

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/hero.html
> +                    <span class="hero-description__topic">Но ты гарантировано наберешь</span>
hero__topic

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/hero.html
> +                    <span class="hero-description__label">+25 баллов</span>
hero__label

2021-04-03 06:58 UTC, kotikm81 commented on src/partials/hero.html
> +            <div class="hero-thumb thumb">
hero__thumb

2021-04-04 14:44 UTC, kotikm81 approved these changes

2021-04-04 14:46 UTC, kotikm81 approved these changes

2021-04-04 14:46 UTC, merged